### ISSUE TITLE
new update breaks the game

### ISSUE THREAD

**Issue by DarknesEagleX** [tn4799/DynamicMissionVehicles#12]
with the 1.2.0.0 update, once you load into the game, your HUD disappears completely and when you move around, your character doesn't stop moving anymore. There are also these messages in the console (see picture)
![FarmingSimulator2022Game_2024-01-26_22-08-43](https://github.com/tn4799/DynamicMissionVehicles/assets/100158513/b575345c-490c-4078-99c8-783a9def0933).
I have no clue what could cause this issue, I do have quite a lot of mods.

**Comment by tn4799** [comment]
A couple of people already reported this issue. 
But till now I could not reproduce the error. 

But I think it somehow causes problems with the platinum addon. Could you try loading the game with the dlc disabled and check if the error still occurs?

**Comment by Be-Mann** [comment]
Same problem for me, I went back to 1.1.0.1, the error is gone there, so the error came from the changes to 1.2.0.0

**Comment by tn4799** [comment]
I've now found the bug after using the update in an already existing savegame of mine. 
Already contacted GIANTS to get the fix out as fast as possible. But since it is weekend at the moment, it probably will take at least till next week. 

But I will already create a release here on github with the hotfix.

**Comment by tn4799** [comment]
Giants released the hotfix
